/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PaymentRouteImport } from './routes/payment'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HomeRouteImport } from './routes/home'
import { Route as ChatsRouteImport } from './routes/chats'
import { Route as BookingsRouteImport } from './routes/bookings'
import { Route as BookingSuccessRouteImport } from './routes/booking-success'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SalonsIdRouteImport } from './routes/salons.$id'
import { Route as ChatBarberIdRouteImport } from './routes/chat.$barberId'
import { Route as BookBarberIdRouteImport } from './routes/book.$barberId'

const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentRoute = PaymentRouteImport.update({
  id: '/payment',
  path: '/payment',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatsRoute = ChatsRouteImport.update({
  id: '/chats',
  path: '/chats',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsRoute = BookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingSuccessRoute = BookingSuccessRouteImport.update({
  id: '/booking-success',
  path: '/booking-success',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SalonsIdRoute = SalonsIdRouteImport.update({
  id: '/salons/$id',
  path: '/salons/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatBarberIdRoute = ChatBarberIdRouteImport.update({
  id: '/chat/$barberId',
  path: '/chat/$barberId',
  getParentRoute: () => rootRouteImport,
} as any)
const BookBarberIdRoute = BookBarberIdRouteImport.update({
  id: '/book/$barberId',
  path: '/book/$barberId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/booking-success': typeof BookingSuccessRoute
  '/bookings': typeof BookingsRoute
  '/chats': typeof ChatsRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/payment': typeof PaymentRoute
  '/profile': typeof ProfileRoute
  '/book/$barberId': typeof BookBarberIdRoute
  '/chat/$barberId': typeof ChatBarberIdRoute
  '/salons/$id': typeof SalonsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/booking-success': typeof BookingSuccessRoute
  '/bookings': typeof BookingsRoute
  '/chats': typeof ChatsRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/payment': typeof PaymentRoute
  '/profile': typeof ProfileRoute
  '/book/$barberId': typeof BookBarberIdRoute
  '/chat/$barberId': typeof ChatBarberIdRoute
  '/salons/$id': typeof SalonsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/booking-success': typeof BookingSuccessRoute
  '/bookings': typeof BookingsRoute
  '/chats': typeof ChatsRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/payment': typeof PaymentRoute
  '/profile': typeof ProfileRoute
  '/book/$barberId': typeof BookBarberIdRoute
  '/chat/$barberId': typeof ChatBarberIdRoute
  '/salons/$id': typeof SalonsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/booking-success'
    | '/bookings'
    | '/chats'
    | '/home'
    | '/login'
    | '/payment'
    | '/profile'
    | '/book/$barberId'
    | '/chat/$barberId'
    | '/salons/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/booking-success'
    | '/bookings'
    | '/chats'
    | '/home'
    | '/login'
    | '/payment'
    | '/profile'
    | '/book/$barberId'
    | '/chat/$barberId'
    | '/salons/$id'
  id:
    | '__root__'
    | '/'
    | '/booking-success'
    | '/bookings'
    | '/chats'
    | '/home'
    | '/login'
    | '/payment'
    | '/profile'
    | '/book/$barberId'
    | '/chat/$barberId'
    | '/salons/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BookingSuccessRoute: typeof BookingSuccessRoute
  BookingsRoute: typeof BookingsRoute
  ChatsRoute: typeof ChatsRoute
  HomeRoute: typeof HomeRoute
  LoginRoute: typeof LoginRoute
  PaymentRoute: typeof PaymentRoute
  ProfileRoute: typeof ProfileRoute
  BookBarberIdRoute: typeof BookBarberIdRoute
  ChatBarberIdRoute: typeof ChatBarberIdRoute
  SalonsIdRoute: typeof SalonsIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment': {
      id: '/payment'
      path: '/payment'
      fullPath: '/payment'
      preLoaderRoute: typeof PaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chats': {
      id: '/chats'
      path: '/chats'
      fullPath: '/chats'
      preLoaderRoute: typeof ChatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings': {
      id: '/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof BookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking-success': {
      id: '/booking-success'
      path: '/booking-success'
      fullPath: '/booking-success'
      preLoaderRoute: typeof BookingSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/salons/$id': {
      id: '/salons/$id'
      path: '/salons/$id'
      fullPath: '/salons/$id'
      preLoaderRoute: typeof SalonsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/$barberId': {
      id: '/chat/$barberId'
      path: '/chat/$barberId'
      fullPath: '/chat/$barberId'
      preLoaderRoute: typeof ChatBarberIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/$barberId': {
      id: '/book/$barberId'
      path: '/book/$barberId'
      fullPath: '/book/$barberId'
      preLoaderRoute: typeof BookBarberIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BookingSuccessRoute: BookingSuccessRoute,
  BookingsRoute: BookingsRoute,
  ChatsRoute: ChatsRoute,
  HomeRoute: HomeRoute,
  LoginRoute: LoginRoute,
  PaymentRoute: PaymentRoute,
  ProfileRoute: ProfileRoute,
  BookBarberIdRoute: BookBarberIdRoute,
  ChatBarberIdRoute: ChatBarberIdRoute,
  SalonsIdRoute: SalonsIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
