/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PaymentRouteImport } from './routes/payment'
import { Route as OwnerRegisterRouteImport } from './routes/owner-register'
import { Route as OwnerPortalRouteImport } from './routes/owner-portal'
import { Route as LoginRouteImport } from './routes/login'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as HomeRouteImport } from './routes/home'
import { Route as ChatsRouteImport } from './routes/chats'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as BookingsRouteImport } from './routes/bookings'
import { Route as BookingSuccessRouteImport } from './routes/booking-success'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OwnerIndexRouteImport } from './routes/owner.index'
import { Route as SalonsIdRouteImport } from './routes/salons.$id'
import { Route as OwnerSettingsRouteImport } from './routes/owner.settings'
import { Route as OwnerServicesRouteImport } from './routes/owner.services'
import { Route as OwnerJobsRouteImport } from './routes/owner.jobs'
import { Route as OwnerBookingsRouteImport } from './routes/owner.bookings'
import { Route as OwnerBarbersRouteImport } from './routes/owner.barbers'
import { Route as JobsIdRouteImport } from './routes/jobs.$id'
import { Route as ChatBarberIdRouteImport } from './routes/chat.$barberId'
import { Route as BookBarberIdRouteImport } from './routes/book.$barberId'

const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentRoute = PaymentRouteImport.update({
  id: '/payment',
  path: '/payment',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerRegisterRoute = OwnerRegisterRouteImport.update({
  id: '/owner-register',
  path: '/owner-register',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerPortalRoute = OwnerPortalRouteImport.update({
  id: '/owner-portal',
  path: '/owner-portal',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatsRoute = ChatsRouteImport.update({
  id: '/chats',
  path: '/chats',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsRoute = BookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingSuccessRoute = BookingSuccessRouteImport.update({
  id: '/booking-success',
  path: '/booking-success',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerIndexRoute = OwnerIndexRouteImport.update({
  id: '/owner/',
  path: '/owner/',
  getParentRoute: () => rootRouteImport,
} as any)
const SalonsIdRoute = SalonsIdRouteImport.update({
  id: '/salons/$id',
  path: '/salons/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerSettingsRoute = OwnerSettingsRouteImport.update({
  id: '/owner/settings',
  path: '/owner/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerServicesRoute = OwnerServicesRouteImport.update({
  id: '/owner/services',
  path: '/owner/services',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerJobsRoute = OwnerJobsRouteImport.update({
  id: '/owner/jobs',
  path: '/owner/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerBookingsRoute = OwnerBookingsRouteImport.update({
  id: '/owner/bookings',
  path: '/owner/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerBarbersRoute = OwnerBarbersRouteImport.update({
  id: '/owner/barbers',
  path: '/owner/barbers',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsIdRoute = JobsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => JobsRoute,
} as any)
const ChatBarberIdRoute = ChatBarberIdRouteImport.update({
  id: '/chat/$barberId',
  path: '/chat/$barberId',
  getParentRoute: () => rootRouteImport,
} as any)
const BookBarberIdRoute = BookBarberIdRouteImport.update({
  id: '/book/$barberId',
  path: '/book/$barberId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/booking-success': typeof BookingSuccessRoute
  '/bookings': typeof BookingsRoute
  '/categories': typeof CategoriesRoute
  '/chats': typeof ChatsRoute
  '/home': typeof HomeRoute
  '/jobs': typeof JobsRouteWithChildren
  '/login': typeof LoginRoute
  '/owner-portal': typeof OwnerPortalRoute
  '/owner-register': typeof OwnerRegisterRoute
  '/payment': typeof PaymentRoute
  '/profile': typeof ProfileRoute
  '/book/$barberId': typeof BookBarberIdRoute
  '/chat/$barberId': typeof ChatBarberIdRoute
  '/jobs/$id': typeof JobsIdRoute
  '/owner/barbers': typeof OwnerBarbersRoute
  '/owner/bookings': typeof OwnerBookingsRoute
  '/owner/jobs': typeof OwnerJobsRoute
  '/owner/services': typeof OwnerServicesRoute
  '/owner/settings': typeof OwnerSettingsRoute
  '/salons/$id': typeof SalonsIdRoute
  '/owner/': typeof OwnerIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/booking-success': typeof BookingSuccessRoute
  '/bookings': typeof BookingsRoute
  '/categories': typeof CategoriesRoute
  '/chats': typeof ChatsRoute
  '/home': typeof HomeRoute
  '/jobs': typeof JobsRouteWithChildren
  '/login': typeof LoginRoute
  '/owner-portal': typeof OwnerPortalRoute
  '/owner-register': typeof OwnerRegisterRoute
  '/payment': typeof PaymentRoute
  '/profile': typeof ProfileRoute
  '/book/$barberId': typeof BookBarberIdRoute
  '/chat/$barberId': typeof ChatBarberIdRoute
  '/jobs/$id': typeof JobsIdRoute
  '/owner/barbers': typeof OwnerBarbersRoute
  '/owner/bookings': typeof OwnerBookingsRoute
  '/owner/jobs': typeof OwnerJobsRoute
  '/owner/services': typeof OwnerServicesRoute
  '/owner/settings': typeof OwnerSettingsRoute
  '/salons/$id': typeof SalonsIdRoute
  '/owner': typeof OwnerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/booking-success': typeof BookingSuccessRoute
  '/bookings': typeof BookingsRoute
  '/categories': typeof CategoriesRoute
  '/chats': typeof ChatsRoute
  '/home': typeof HomeRoute
  '/jobs': typeof JobsRouteWithChildren
  '/login': typeof LoginRoute
  '/owner-portal': typeof OwnerPortalRoute
  '/owner-register': typeof OwnerRegisterRoute
  '/payment': typeof PaymentRoute
  '/profile': typeof ProfileRoute
  '/book/$barberId': typeof BookBarberIdRoute
  '/chat/$barberId': typeof ChatBarberIdRoute
  '/jobs/$id': typeof JobsIdRoute
  '/owner/barbers': typeof OwnerBarbersRoute
  '/owner/bookings': typeof OwnerBookingsRoute
  '/owner/jobs': typeof OwnerJobsRoute
  '/owner/services': typeof OwnerServicesRoute
  '/owner/settings': typeof OwnerSettingsRoute
  '/salons/$id': typeof SalonsIdRoute
  '/owner/': typeof OwnerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/booking-success'
    | '/bookings'
    | '/categories'
    | '/chats'
    | '/home'
    | '/jobs'
    | '/login'
    | '/owner-portal'
    | '/owner-register'
    | '/payment'
    | '/profile'
    | '/book/$barberId'
    | '/chat/$barberId'
    | '/jobs/$id'
    | '/owner/barbers'
    | '/owner/bookings'
    | '/owner/jobs'
    | '/owner/services'
    | '/owner/settings'
    | '/salons/$id'
    | '/owner/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/booking-success'
    | '/bookings'
    | '/categories'
    | '/chats'
    | '/home'
    | '/jobs'
    | '/login'
    | '/owner-portal'
    | '/owner-register'
    | '/payment'
    | '/profile'
    | '/book/$barberId'
    | '/chat/$barberId'
    | '/jobs/$id'
    | '/owner/barbers'
    | '/owner/bookings'
    | '/owner/jobs'
    | '/owner/services'
    | '/owner/settings'
    | '/salons/$id'
    | '/owner'
  id:
    | '__root__'
    | '/'
    | '/booking-success'
    | '/bookings'
    | '/categories'
    | '/chats'
    | '/home'
    | '/jobs'
    | '/login'
    | '/owner-portal'
    | '/owner-register'
    | '/payment'
    | '/profile'
    | '/book/$barberId'
    | '/chat/$barberId'
    | '/jobs/$id'
    | '/owner/barbers'
    | '/owner/bookings'
    | '/owner/jobs'
    | '/owner/services'
    | '/owner/settings'
    | '/salons/$id'
    | '/owner/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BookingSuccessRoute: typeof BookingSuccessRoute
  BookingsRoute: typeof BookingsRoute
  CategoriesRoute: typeof CategoriesRoute
  ChatsRoute: typeof ChatsRoute
  HomeRoute: typeof HomeRoute
  JobsRoute: typeof JobsRouteWithChildren
  LoginRoute: typeof LoginRoute
  OwnerPortalRoute: typeof OwnerPortalRoute
  OwnerRegisterRoute: typeof OwnerRegisterRoute
  PaymentRoute: typeof PaymentRoute
  ProfileRoute: typeof ProfileRoute
  BookBarberIdRoute: typeof BookBarberIdRoute
  ChatBarberIdRoute: typeof ChatBarberIdRoute
  OwnerBarbersRoute: typeof OwnerBarbersRoute
  OwnerBookingsRoute: typeof OwnerBookingsRoute
  OwnerJobsRoute: typeof OwnerJobsRoute
  OwnerServicesRoute: typeof OwnerServicesRoute
  OwnerSettingsRoute: typeof OwnerSettingsRoute
  SalonsIdRoute: typeof SalonsIdRoute
  OwnerIndexRoute: typeof OwnerIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment': {
      id: '/payment'
      path: '/payment'
      fullPath: '/payment'
      preLoaderRoute: typeof PaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner-register': {
      id: '/owner-register'
      path: '/owner-register'
      fullPath: '/owner-register'
      preLoaderRoute: typeof OwnerRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner-portal': {
      id: '/owner-portal'
      path: '/owner-portal'
      fullPath: '/owner-portal'
      preLoaderRoute: typeof OwnerPortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chats': {
      id: '/chats'
      path: '/chats'
      fullPath: '/chats'
      preLoaderRoute: typeof ChatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings': {
      id: '/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof BookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking-success': {
      id: '/booking-success'
      path: '/booking-success'
      fullPath: '/booking-success'
      preLoaderRoute: typeof BookingSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/': {
      id: '/owner/'
      path: '/owner'
      fullPath: '/owner/'
      preLoaderRoute: typeof OwnerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/salons/$id': {
      id: '/salons/$id'
      path: '/salons/$id'
      fullPath: '/salons/$id'
      preLoaderRoute: typeof SalonsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/settings': {
      id: '/owner/settings'
      path: '/owner/settings'
      fullPath: '/owner/settings'
      preLoaderRoute: typeof OwnerSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/services': {
      id: '/owner/services'
      path: '/owner/services'
      fullPath: '/owner/services'
      preLoaderRoute: typeof OwnerServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/jobs': {
      id: '/owner/jobs'
      path: '/owner/jobs'
      fullPath: '/owner/jobs'
      preLoaderRoute: typeof OwnerJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/bookings': {
      id: '/owner/bookings'
      path: '/owner/bookings'
      fullPath: '/owner/bookings'
      preLoaderRoute: typeof OwnerBookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/barbers': {
      id: '/owner/barbers'
      path: '/owner/barbers'
      fullPath: '/owner/barbers'
      preLoaderRoute: typeof OwnerBarbersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/$id': {
      id: '/jobs/$id'
      path: '/$id'
      fullPath: '/jobs/$id'
      preLoaderRoute: typeof JobsIdRouteImport
      parentRoute: typeof JobsRoute
    }
    '/chat/$barberId': {
      id: '/chat/$barberId'
      path: '/chat/$barberId'
      fullPath: '/chat/$barberId'
      preLoaderRoute: typeof ChatBarberIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/$barberId': {
      id: '/book/$barberId'
      path: '/book/$barberId'
      fullPath: '/book/$barberId'
      preLoaderRoute: typeof BookBarberIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface JobsRouteChildren {
  JobsIdRoute: typeof JobsIdRoute
}

const JobsRouteChildren: JobsRouteChildren = {
  JobsIdRoute: JobsIdRoute,
}

const JobsRouteWithChildren = JobsRoute._addFileChildren(JobsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BookingSuccessRoute: BookingSuccessRoute,
  BookingsRoute: BookingsRoute,
  CategoriesRoute: CategoriesRoute,
  ChatsRoute: ChatsRoute,
  HomeRoute: HomeRoute,
  JobsRoute: JobsRouteWithChildren,
  LoginRoute: LoginRoute,
  OwnerPortalRoute: OwnerPortalRoute,
  OwnerRegisterRoute: OwnerRegisterRoute,
  PaymentRoute: PaymentRoute,
  ProfileRoute: ProfileRoute,
  BookBarberIdRoute: BookBarberIdRoute,
  ChatBarberIdRoute: ChatBarberIdRoute,
  OwnerBarbersRoute: OwnerBarbersRoute,
  OwnerBookingsRoute: OwnerBookingsRoute,
  OwnerJobsRoute: OwnerJobsRoute,
  OwnerServicesRoute: OwnerServicesRoute,
  OwnerSettingsRoute: OwnerSettingsRoute,
  SalonsIdRoute: SalonsIdRoute,
  OwnerIndexRoute: OwnerIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
